import { describe, it, expect, vi, afterEach } from 'vitest';
import { EdgeBlockedError } from '@chrischall/mcp-utils';
import { createTestHarness, parseToolResult } from '@chrischall/mcp-utils/test';
import { SignUpGeniusClient, AuthError } from '../src/client.js';
import { registerHealthcheckTools } from '../src/tools/healthcheck.js';
import type { KeyAccount, SessionAccount } from '../src/config.js';

/**
 * A CDN/WAF block is not a rejected credential (chrischall/mcp-host#1015).
 *
 * parseEnvelope turned every 403 into AuthError — status 403, no body — so
 * the shared healthcheck read an edge's refusal page as `credential_rejected`
 * and told the user to check SIGNUPGENIUS_USER_KEY / sign in again, though the
 * request never reached SignUpGenius. These run the REAL client against
 * CloudFront's block page.
 */

// CloudFront's block page, as served (whitespace trimmed, ids made up).
const CLOUDFRONT_BLOCK =
  '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">' +
  '<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">' +
  '<TITLE>ERROR: The request could not be satisfied</TITLE></HEAD><BODY>' +
  '<H1>403 ERROR</H1><H2>The request could not be satisfied.</H2><HR noshade size="1px">' +
  "Request blocked. We can't connect to the server for this app or website at this time. " +
  'There might be too much traffic or a configuration error. Try again later, or contact the app or ' +
  'website owner.<BR clear="all"><HR noshade size="1px"><PRE>Generated by cloudfront (CloudFront)\n' +
  'Request ID: AbCdEfGhIjKlMnOpQrStUvWxYz0123456789abcdefghijklmnopqr==</PRE><ADDRESS></ADDRESS></BODY></HTML>';

const blocked = () =>
  new Response(CLOUDFRONT_BLOCK, {
    status: 403,
    headers: { 'content-type': 'text/html', 'x-cache': 'Error from cloudfront' },
  });

const keyAccount: KeyAccount = {
  mode: 'key',
  name: 'sug',
  baseUrl: 'https://api.signupgenius.com/v2/k',
  userKey: 'KEY',
};

const sessionAccount: SessionAccount = {
  mode: 'session',
  name: 'me@x.com',
  baseUrl: 'https://api.signupgenius.com/v3',
  legacyBaseUrl: 'https://www.signupgenius.com',
  loginBaseUrl: 'https://www.signupgenius.com',
  email: 'me@x.com',
  password: 'pw',
};

interface Result {
  ok: boolean;
  error?: { kind: string; message: string };
  hint: string;
}

async function healthcheck(client: SignUpGeniusClient): Promise<Result> {
  const h = await createTestHarness((server) => registerHealthcheckTools(server, client));
  const res = await h.client.callTool({ name: 'signupgenius_healthcheck', arguments: {} });
  await h.close?.();
  return parseToolResult<Result>(res as never);
}

afterEach(() => vi.restoreAllMocks());

describe('a CloudFront block reads as edge_blocked, not a rejected credential', () => {
  it('key mode: on the /user/profile probe', async () => {
    vi.spyOn(globalThis, 'fetch').mockImplementation(async () => blocked());

    const r = await healthcheck(new SignUpGeniusClient(keyAccount));

    expect(r.ok).toBe(false);
    expect(r.error?.kind).toBe('edge_blocked');
    expect(r.hint).not.toMatch(/SIGNUPGENIUS_USER_KEY/);
  });

  it('session mode: on the /member/profile probe, with no re-login', async () => {
    const fetchSpy = vi.spyOn(globalThis, 'fetch').mockImplementation(async () => blocked());
    const sessionLogin = vi.fn(async () => ({ accessToken: 'jwt', cookieHeader: 'c=1' }));

    const r = await healthcheck(new SignUpGeniusClient(sessionAccount, { sessionLogin }));

    expect(r.error?.kind).toBe('edge_blocked');
    // One login to mint the session, then the blocked probe — a block is not
    // an expiry, so no second login.
    expect(sessionLogin).toHaveBeenCalledTimes(1);
    expect(fetchSpy).toHaveBeenCalledTimes(1);
  });

  it('tool calls surface the block, not the check-your-key AuthError', async () => {
    vi.spyOn(globalThis, 'fetch').mockImplementation(async () => blocked());

    const err = await new SignUpGeniusClient(keyAccount).request('/user/profile').catch((e: unknown) => e);

    expect(err).toBeInstanceOf(EdgeBlockedError);
    expect((err as EdgeBlockedError).status).toBe(403);
    expect(err).not.toBeInstanceOf(AuthError);
  });

  it('control: a JSON 403 from SignUpGenius is still a rejected credential', async () => {
    vi.spyOn(globalThis, 'fetch').mockImplementation(
      async () =>
        new Response(JSON.stringify({ data: null, message: ['bad key'], success: false }), {
          status: 403,
          headers: { 'content-type': 'application/json' },
        }),
    );

    const r = await healthcheck(new SignUpGeniusClient(keyAccount));

    expect(r.error?.kind).toBe('credential_rejected');
  });
});
